---
version: "3.4"
services:
  web:
    image: "uwcirg/medc:${DOCKER_IMAGE_TAG:-develop}"
    build:
      context: .
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-5000}:5000
